name: trigger-pr-release

on:
  pull_request:

jobs:
  trigger-pr-release:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: buildpr
          repository: adamsilverstein/site-kit-wp-builds
          client-payload: '{"ref": "${{ github.ref }}"}'
