name: build-pr-release

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build-pr-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Composer Install
      uses: php-actions/composer@v1
      with:
        args: install
    - name: Setup Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Cache Node - npm
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-cache-
    - name: npm/Gulp Install
      run: |
        npm install
        npm install gulp-cli -g
    - name: Build develop version
      run: |
        npm run build:dev
        gulp release
        gulp copy
        gulp pre-zip
        gulp zip
        mv google-site-kit.zip google-site-kit-dev.zip
    - name: Build release version
      run: |
        npm run build
        gulp release
        gulp copy
        gulp pre-zip
        gulp zip
    - name: Deploy build files to wiki
      run: |
        mkdir -p ${{ github.ref }}
        mv google-site-kit.zip ${{ github.ref }}
        mv google-site-kit-dev.zip ${{ github.ref }}
        bash .github/release-to-wiki.sh ${{ github.ref }}
      env:
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
