name: WordPress 4.9
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
env:
  E2E=1
  WP_VERSION=4.9.16
  GUTENBERG_VERSION=4.9.0
jobs:
  e2e:
    name: E2E Tests (WordPress 4.9.16, Gutenberg 4.9.0)
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
